# mergekit-yaml scripts/mergekit-configs/ties/auto_created/ties-daves-tulu-0.5-science-2500-0.5.yaml /net/nfs.cirrascale/allennlp/jacobm/modular_adaptation/checkpoints/domain_addition/with_daves_tulu_model/ties-0.5-tulu_only-0.5-science_2500 --cuda &&
# mergekit-yaml scripts/mergekit-configs/ties/auto_created/ties-daves-tulu-0.84-science-2500-0.16.yaml /net/nfs.cirrascale/allennlp/jacobm/modular_adaptation/checkpoints/domain_addition/with_daves_tulu_model/ties-0.84-tulu_only-0.16-science_2500 --cuda &&
# mergekit-yaml scripts/mergekit-configs/dare_ties/auto_created/dare_ties-daves-tulu-0.5-science-2500-0.5.yaml /net/nfs.cirrascale/allennlp/jacobm/modular_adaptation/checkpoints/domain_addition/with_daves_tulu_model/dare_ties-0.5-tulu_only-0.5-science_2500 --cuda &&
# mergekit-yaml scripts/mergekit-configs/dare_ties/auto_created/dare_ties-daves-tulu-0.84-science-2500-0.16.yaml /net/nfs.cirrascale/allennlp/jacobm/modular_adaptation/checkpoints/domain_addition/with_daves_tulu_model/dare_ties-0.84-tulu_only-0.16-science_2500 --cuda &&
# mergekit-yaml scripts/mergekit-configs/dare_linear/auto_created/dare_linear-daves-tulu-0.5-science-2500-0.5.yaml /net/nfs.cirrascale/allennlp/jacobm/modular_adaptation/checkpoints/domain_addition/with_daves_tulu_model/dare_linear-0.5-tulu_only-0.5-science_2500 --cuda &&
# mergekit-yaml scripts/mergekit-configs/dare_linear/auto_created/dare_linear-daves-tulu-0.84-science-2500-0.16.yaml /net/nfs.cirrascale/allennlp/jacobm/modular_adaptation/checkpoints/domain_addition/with_daves_tulu_model/dare_linear-0.84-tulu_only-0.16-science_2500 --cuda &&
mergekit-yaml scripts/mergekit-configs/ties/auto_created/ties-daves-tulu-0.9-science-2500-0.1.yaml /net/nfs.cirrascale/allennlp/jacobm/modular_adaptation/checkpoints/domain_addition/with_daves_tulu_model/ties-0.9-tulu_only-0.1-science_2500 --cuda &&
mergekit-yaml scripts/mergekit-configs/ties/auto_created/ties-daves-tulu-0.8-science-2500-0.2.yaml /net/nfs.cirrascale/allennlp/jacobm/modular_adaptation/checkpoints/domain_addition/with_daves_tulu_model/ties-0.8-tulu_only-0.2-science_2500 --cuda &&
mergekit-yaml scripts/mergekit-configs/ties/auto_created/ties-daves-tulu-0.7-science-2500-0.3.yaml /net/nfs.cirrascale/allennlp/jacobm/modular_adaptation/checkpoints/domain_addition/with_daves_tulu_model/ties-0.7-tulu_only-0.3-science_2500 --cuda &&
mergekit-yaml scripts/mergekit-configs/ties/auto_created/ties-daves-tulu-0.6-science-2500-0.4.yaml /net/nfs.cirrascale/allennlp/jacobm/modular_adaptation/checkpoints/domain_addition/with_daves_tulu_model/ties-0.6-tulu_only-0.4-science_2500 --cuda &&
mergekit-yaml scripts/mergekit-configs/ties/auto_created/ties-daves-tulu-0.4-science-2500-0.6.yaml /net/nfs.cirrascale/allennlp/jacobm/modular_adaptation/checkpoints/domain_addition/with_daves_tulu_model/ties-0.4-tulu_only-0.6-science_2500 --cuda &&
mergekit-yaml scripts/mergekit-configs/ties/auto_created/ties-daves-tulu-0.3-science-2500-0.7.yaml /net/nfs.cirrascale/allennlp/jacobm/modular_adaptation/checkpoints/domain_addition/with_daves_tulu_model/ties-0.3-tulu_only-0.7-science_2500 --cuda &&
mergekit-yaml scripts/mergekit-configs/ties/auto_created/ties-daves-tulu-0.2-science-2500-0.8.yaml /net/nfs.cirrascale/allennlp/jacobm/modular_adaptation/checkpoints/domain_addition/with_daves_tulu_model/ties-0.2-tulu_only-0.8-science_2500 --cuda &&
mergekit-yaml scripts/mergekit-configs/ties/auto_created/ties-daves-tulu-0.1-science-2500-0.9.yaml /net/nfs.cirrascale/allennlp/jacobm/modular_adaptation/checkpoints/domain_addition/with_daves_tulu_model/ties-0.1-tulu_only-0.9-science_2500 --cuda &&
mergekit-yaml scripts/mergekit-configs/dare_ties/auto_created/dare_ties-daves-tulu-0.9-science-2500-0.1.yaml /net/nfs.cirrascale/allennlp/jacobm/modular_adaptation/checkpoints/domain_addition/with_daves_tulu_model/dare_ties-0.9-tulu_only-0.1-science_2500 --cuda &&
mergekit-yaml scripts/mergekit-configs/dare_ties/auto_created/dare_ties-daves-tulu-0.8-science-2500-0.2.yaml /net/nfs.cirrascale/allennlp/jacobm/modular_adaptation/checkpoints/domain_addition/with_daves_tulu_model/dare_ties-0.8-tulu_only-0.2-science_2500 --cuda &&
mergekit-yaml scripts/mergekit-configs/dare_ties/auto_created/dare_ties-daves-tulu-0.7-science-2500-0.3.yaml /net/nfs.cirrascale/allennlp/jacobm/modular_adaptation/checkpoints/domain_addition/with_daves_tulu_model/dare_ties-0.7-tulu_only-0.3-science_2500 --cuda &&
mergekit-yaml scripts/mergekit-configs/dare_ties/auto_created/dare_ties-daves-tulu-0.6-science-2500-0.4.yaml /net/nfs.cirrascale/allennlp/jacobm/modular_adaptation/checkpoints/domain_addition/with_daves_tulu_model/dare_ties-0.6-tulu_only-0.4-science_2500 --cuda &&
mergekit-yaml scripts/mergekit-configs/dare_ties/auto_created/dare_ties-daves-tulu-0.4-science-2500-0.6.yaml /net/nfs.cirrascale/allennlp/jacobm/modular_adaptation/checkpoints/domain_addition/with_daves_tulu_model/dare_ties-0.4-tulu_only-0.6-science_2500 --cuda &&
mergekit-yaml scripts/mergekit-configs/dare_ties/auto_created/dare_ties-daves-tulu-0.3-science-2500-0.7.yaml /net/nfs.cirrascale/allennlp/jacobm/modular_adaptation/checkpoints/domain_addition/with_daves_tulu_model/dare_ties-0.3-tulu_only-0.7-science_2500 --cuda &&
mergekit-yaml scripts/mergekit-configs/dare_ties/auto_created/dare_ties-daves-tulu-0.2-science-2500-0.8.yaml /net/nfs.cirrascale/allennlp/jacobm/modular_adaptation/checkpoints/domain_addition/with_daves_tulu_model/dare_ties-0.2-tulu_only-0.8-science_2500 --cuda &&
mergekit-yaml scripts/mergekit-configs/dare_ties/auto_created/dare_ties-daves-tulu-0.1-science-2500-0.9.yaml /net/nfs.cirrascale/allennlp/jacobm/modular_adaptation/checkpoints/domain_addition/with_daves_tulu_model/dare_ties-0.1-tulu_only-0.9-science_2500 --cuda &&
mergekit-yaml scripts/mergekit-configs/dare_linear/auto_created/dare_linear-daves-tulu-0.9-science-2500-0.1.yaml /net/nfs.cirrascale/allennlp/jacobm/modular_adaptation/checkpoints/domain_addition/with_daves_tulu_model/dare_linear-0.9-tulu_only-0.1-science_2500 --cuda &&
mergekit-yaml scripts/mergekit-configs/dare_linear/auto_created/dare_linear-daves-tulu-0.8-science-2500-0.2.yaml /net/nfs.cirrascale/allennlp/jacobm/modular_adaptation/checkpoints/domain_addition/with_daves_tulu_model/dare_linear-0.8-tulu_only-0.2-science_2500 --cuda &&
mergekit-yaml scripts/mergekit-configs/dare_linear/auto_created/dare_linear-daves-tulu-0.7-science-2500-0.3.yaml /net/nfs.cirrascale/allennlp/jacobm/modular_adaptation/checkpoints/domain_addition/with_daves_tulu_model/dare_linear-0.7-tulu_only-0.3-science_2500 --cuda &&
mergekit-yaml scripts/mergekit-configs/dare_linear/auto_created/dare_linear-daves-tulu-0.6-science-2500-0.4.yaml /net/nfs.cirrascale/allennlp/jacobm/modular_adaptation/checkpoints/domain_addition/with_daves_tulu_model/dare_linear-0.6-tulu_only-0.4-science_2500 --cuda &&
mergekit-yaml scripts/mergekit-configs/dare_linear/auto_created/dare_linear-daves-tulu-0.4-science-2500-0.6.yaml /net/nfs.cirrascale/allennlp/jacobm/modular_adaptation/checkpoints/domain_addition/with_daves_tulu_model/dare_linear-0.4-tulu_only-0.6-science_2500 --cuda &&
mergekit-yaml scripts/mergekit-configs/dare_linear/auto_created/dare_linear-daves-tulu-0.3-science-2500-0.7.yaml /net/nfs.cirrascale/allennlp/jacobm/modular_adaptation/checkpoints/domain_addition/with_daves_tulu_model/dare_linear-0.3-tulu_only-0.7-science_2500 --cuda &&
mergekit-yaml scripts/mergekit-configs/dare_linear/auto_created/dare_linear-daves-tulu-0.2-science-2500-0.8.yaml /net/nfs.cirrascale/allennlp/jacobm/modular_adaptation/checkpoints/domain_addition/with_daves_tulu_model/dare_linear-0.2-tulu_only-0.8-science_2500 --cuda &&
mergekit-yaml scripts/mergekit-configs/dare_linear/auto_created/dare_linear-daves-tulu-0.1-science-2500-0.9.yaml /net/nfs.cirrascale/allennlp/jacobm/modular_adaptation/checkpoints/domain_addition/with_daves_tulu_model/dare_linear-0.1-tulu_only-0.9-science_2500 --cuda &&
mergekit-yaml scripts/mergekit-configs/slerp_merges/auto_created/slerp-daves-tulu-0.9-science-2500-0.1.yaml /net/nfs.cirrascale/allennlp/jacobm/modular_adaptation/checkpoints/domain_addition/with_daves_tulu_model/slerp-0.9-tulu_only-0.1-science_2500 --cuda &&
mergekit-yaml scripts/mergekit-configs/slerp_merges/auto_created/slerp-daves-tulu-0.8-science-2500-0.2.yaml /net/nfs.cirrascale/allennlp/jacobm/modular_adaptation/checkpoints/domain_addition/with_daves_tulu_model/slerp-0.8-tulu_only-0.2-science_2500 --cuda &&
mergekit-yaml scripts/mergekit-configs/slerp_merges/auto_created/slerp-daves-tulu-0.7-science-2500-0.3.yaml /net/nfs.cirrascale/allennlp/jacobm/modular_adaptation/checkpoints/domain_addition/with_daves_tulu_model/slerp-0.7-tulu_only-0.3-science_2500 --cuda &&
mergekit-yaml scripts/mergekit-configs/slerp_merges/auto_created/slerp-daves-tulu-0.6-science-2500-0.4.yaml /net/nfs.cirrascale/allennlp/jacobm/modular_adaptation/checkpoints/domain_addition/with_daves_tulu_model/slerp-0.6-tulu_only-0.4-science_2500 --cuda &&
mergekit-yaml scripts/mergekit-configs/slerp_merges/auto_created/slerp-daves-tulu-0.5-science-2500-0.5.yaml /net/nfs.cirrascale/allennlp/jacobm/modular_adaptation/checkpoints/domain_addition/with_daves_tulu_model/slerp-0.5-tulu_only-0.5-science_2500 --cuda &&
mergekit-yaml scripts/mergekit-configs/slerp_merges/auto_created/slerp-daves-tulu-0.4-science-2500-0.6.yaml /net/nfs.cirrascale/allennlp/jacobm/modular_adaptation/checkpoints/domain_addition/with_daves_tulu_model/slerp-0.4-tulu_only-0.6-science_2500 --cuda &&
mergekit-yaml scripts/mergekit-configs/slerp_merges/auto_created/slerp-daves-tulu-0.3-science-2500-0.7.yaml /net/nfs.cirrascale/allennlp/jacobm/modular_adaptation/checkpoints/domain_addition/with_daves_tulu_model/slerp-0.3-tulu_only-0.7-science_2500 --cuda &&
mergekit-yaml scripts/mergekit-configs/slerp_merges/auto_created/slerp-daves-tulu-0.2-science-2500-0.8.yaml /net/nfs.cirrascale/allennlp/jacobm/modular_adaptation/checkpoints/domain_addition/with_daves_tulu_model/slerp-0.2-tulu_only-0.8-science_2500 --cuda &&
mergekit-yaml scripts/mergekit-configs/slerp_merges/auto_created/slerp-daves-tulu-0.1-science-2500-0.9.yaml /net/nfs.cirrascale/allennlp/jacobm/modular_adaptation/checkpoints/domain_addition/with_daves_tulu_model/slerp-0.1-tulu_only-0.9-science_2500 --cuda &&
mergekit-yaml scripts/mergekit-configs/slerp_merges/auto_created/slerp-daves-tulu-0.84-science-2500-0.16.yaml /net/nfs.cirrascale/allennlp/jacobm/modular_adaptation/checkpoints/domain_addition/with_daves_tulu_model/slerp-0.84-tulu_only-0.16-science_2500 --cuda